image: python:latest

before_script:
  - pip install --upgrade pip
  - pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin

build-docs:
  stage: build
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
      - site
    expire_in: 1 week
  only:
    - main

pages:
  stage: deploy
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
    - public
  only:
      - main

