site_name: JR-ETES-DOCS

theme:
  name: simple-blog
  highlightjs: true
    - yaml
    - bash
    - php
    - html
  admonition:
      <type>: <icon>
  sidebar: true
  navigation_depth: 3
  components:
    footer: false
  site_name_style: overline
  theme_style: light

docs_dir: src

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Page01:
    - SubPage01:
      - SubPage01: page01/docs/documentation.md
  - Page02:
    - Page02: Page02/docs/documentation.md
