site_name: JR-ETES-DOCS

theme:
  name: simple-blog
  highlightjs: true
    - yaml
    - bash
    - php
    - html
  admonition:
      <type>: <icon>
  sidebar: true
  navigation_depth: 2
  components:
    footer: false
  site_name_style: overline
  theme_style: dark

docs_dir: src

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Edira:
    - Breakdowns:
      - Directory Structure & Responsibilties: edira/project-breakdown/docs/structure.md
    - Issues:
      - 131 VVT Admin Dashboard Show VVTs: edira/issue-131/docs/documentation.md
      - 159 VVT Create Notification: edira/issue-159/docs/documentation.md
      - 169 VVT Highlight After Creation: edira/issue-169/docs/documentation.md
      - 336 SOA Version Update: edira/issue-336/docs/02_documentation.md
      - 338 Admin Advanced Search Filter: edira/issue-338/docs/documentation.md
      - 373 Company Settings Rework: 
        - 373 Master Records Rework:
          - 373 Company Information: edira/issue-373/docs/documentation.md
      - 382 VVT Kapitel: edira/issue-382/docs/documentation.md
      - 383 VVT Overview Content Preview: edira/issue-383/docs/documentation.md
  - Setup:
    - Edira Development Setup: setup/edira-dev-env/docs/documentation.md
    - Edira Git Guide: setup/git/docs/documentation.md
  - Education:
    - ETES Internal Courses:
      - BD01: education/etes-edu/BD01/docs/documentation.md
    - Laracast:
      - Git: education/laracast/git/docs/documentation.md
      - Laravel: education/laracast/laravel/docs/documentation.md
      - Livewire: education/laracast/livewire/docs/documentation.md
      - PHP: education/laracast/php/docs/documentation.md
