site_name: JR-DOCS

theme:
  name: simple-blog
  highlightjs: true
    - yaml
    - bash
    - php
    - html
  admonition:
      <type>: <icon>
  sidebar: true
  navigation_depth: 3
  components:
    footer: false
  site_name_style: overline
  theme_style: light

docs_dir: src

watch:
  - src

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Page01:
    - SubPage01:
      - SubPage01: md/page01/docs/documentation.md
      - SubPage02: md/page01/docs/documentation.md
  - Page02:
    - Page02: md/page02/docs/documentation.md
